"""Reset final com todas as tabelas

Revision ID: d0f7bc910ced
Revises: 
Create Date: 2025-10-30 17:00:15.384118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f7bc910ced'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco_venda_estimado_brl', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('item_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('produto_catalogo_id', sa.Integer(), nullable=False),
    sa.Column('preco_compra_usd', sa.Float(), nullable=False),
    sa.Column('peso_kg', sa.Float(), nullable=False),
    sa.Column('iof_percent', sa.Float(), nullable=False),
    sa.Column('taxa_dolar', sa.Float(), nullable=False),
    sa.Column('shipping_method', sa.String(length=50), nullable=False),
    sa.Column('custo_produto_brl', sa.Float(), nullable=False),
    sa.Column('custo_iof_brl', sa.Float(), nullable=False),
    sa.Column('custo_frete_brl', sa.Float(), nullable=False),
    sa.Column('custo_total_brl', sa.Float(), nullable=False),
    sa.Column('lucro_estimado_brl', sa.Float(), nullable=False),
    sa.Column('lucro_estimado_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['produto_catalogo_id'], ['produto_catalogo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=False),
    sa.Column('preco_venda_final_brl', sa.Float(), nullable=False),
    sa.Column('lucro_real_brl', sa.Float(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item_estoque.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('transacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_brl', sa.Float(), nullable=False),
    sa.Column('item_estoque_id', sa.Integer(), nullable=True),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['item_estoque_id'], ['item_estoque.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_a_pagar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_brl', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_a_receber',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_parcela_brl', sa.Float(), nullable=False),
    sa.Column('data_vencimento', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('transacao_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transacao_id'], ['transacao.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['venda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lote_de_custo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor_total_brl', sa.Float(), nullable=False),
    sa.Column('metodo_rateio', sa.String(length=50), nullable=False),
    sa.Column('conta_a_pagar_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conta_a_pagar_id'], ['conta_a_pagar.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conta_a_pagar_id')
    )
    op.create_table('alocacao_custo_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lote_id', sa.Integer(), nullable=False),
    sa.Column('item_estoque_id', sa.Integer(), nullable=False),
    sa.Column('valor_alocado_brl', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_estoque_id'], ['item_estoque.id'], ),
    sa.ForeignKeyConstraint(['lote_id'], ['lote_de_custo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alocacao_custo_item')
    op.drop_table('lote_de_custo')
    op.drop_table('conta_a_receber')
    op.drop_table('conta_a_pagar')
    op.drop_table('transacao')
    op.drop_table('venda')
    op.drop_table('item_estoque')
    op.drop_table('produto_catalogo')
    # ### end Alembic commands ###
